default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wings_order_form_development

test:
  <<: *default
  database: wings_order_form_test

production:
  <<: *default
  database: wings_order_form_production
  username: wings_order_form
  password: <%= ENV['WINGS_ORDER_FORM_DATABASE_PASSWORD'] %>
